travis:
  secure:
    BINSTAR_TOKEN: riREIQbFBynCRkKZ1vbm/arWqjipHR0SMO5D7WNlh/UFtOdYoHTT6jWbi/W+W4+YrrDpUK7HK2NGFhlKM8ODl3jOE/KqFNKM6W1YHpoF8CFjn2egqizggGYaSfwAzvU/pA/pi2RDxqb8SyGYcpqF7peqe+Hg9vUZ4qdvtkfLDDSCEiYToBhIO/RJCUMnKkclt6tPX9DsBSj+MpDwEqjclAmmhRiouxSgDJGFm6zQWRi+iE6hrZep+YAzaaze2fWw5z+s75VP384wFM7BeG7J2sz8HO0Sn6kBkZijJAFfi7mvlVC0Kuu8r93guMfuXHEeAIsvdXyXSHBmFl4TMjWxIMtqJEAE/alV1gPFBAiSk75APYjjO1S68bHVcaQHEH1K7NuJ+zU+Q3RXqnfFJ4iLtH3rJPtkTnjf2bHGSnrBMsovwwmtU//qCBAK3S/hcLJUthgane+IMAhiuBMBbCriK08cMdW4t/bHdN4YweuRziqN1V73O0KI+tWFjSdgPJEhNAZ13GKeJriy7Nt2XfUlXeO3qoT1KtfO5CicZKxdx9BdmpWXg9/YBp2tmLc49K+txW21MdD+R5g68zaqkiUscGL43zPVrKSvIjzSYqqhmsXZ2D//QD/FqPdvCaWnmthHA58KAjKpeXkRxoXrz5H0W46jG3V5qWPFNbnuGaxw4nM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
